---

- hosts: myhosts
  user: vagrant
  sudo: True

  vars:
    repository_basedir: ../../ansible-repository
    bootstrap_upgrade: True
    # IPs allowed to access the status pages
    nginx_status_ranges: ["127.0.0.1", "192.168.1.0/24"]

    # Load PHP-FPM specific config.
    nginx_fcgi_fpm: True

    # Define FCGI Upstream servers.
    nginx_fastcgi_upstreams:
    - name: www
      keepalive: 5
      servers: ["unix:/var/run/php5-fpm-www.sock"]

    # FPM Pools used as upstream for nginx
    php_fpm_pools:
    - name: www
      user: www-data
      group: www-data
      status: True

  tasks: 
  # Update APT Caches and install base tools
  - include: $repository_basedir/bootstrap/tasks/setup.yml

  # Install PHP cli & FPM with a default pool
  - include: $repository_basedir/php/tasks/setup.yml
  - include: $repository_basedir/php/tasks/php-fpm.yml

  # Install nginx and a example server using the default fpm pool
  - include: $repository_basedir/nginx/tasks/setup.yml
  - include: $repository_basedir/nginx/tasks/server_add.yml create_root=true name=test.webdev.vt root=/vagrant/www type=php upstream=www

  handlers:
  - include: $repository_basedir/nginx/handlers/handlers.yml
  - include: $repository_basedir/php/handlers/handlers.yml

